project:
  type: book

lang: pt-BR

book:
  title: Métodos Computacionais para Indicadores Sociais e Políticas Públicas
  subtitle: Usando R  
  author: Ronaldo Baltar e Cláudia Baltar
  date: today
  date-format: 'YYYY'
  publisher: Editora IHC
  publisher-place: Londrina
  chapters:
    - index.qmd
    - part: Fundamentos
      chapters:
        - intro.qmd
        - modelo.qmd
        - cap_01_indicadores_com_r.qmd
    - part: Referências
      chapters:
      - references.qmd
      - sobre_os_autores.qmd

format:
  html:
    theme: cosmo
    code-copy: true

  pdf:
    documentclass: scrbook    
    papersize: a4
    fontsize: 11pt
    classoption:
      - open = right
      - twoside = true
    mainfont: "TeX Gyre Termes"
    sansfont: "Fira Sans"
    monofont: "Fira Mono"
    mathfont: "Fira Math" 
    highlight-style: github
    #code-block-border-left: true
    #code-block-bg: true
    code-line-numbers: true
    biblio-method: biblatex
    biblio-style: abnt
    biblatexoptions: [autolang=babel] 
    # Margens ao estilo Tufte book
    geometry:
      - "top=2.5cm"
      - "bottom=2.5cm"
      - "inner=3cm"          # Margem interna para encadernação
      - "textwidth=12cm"     # Largura do bloco de texto principal
      - "marginparwidth=4.5cm"   # LARGURA DA MARGEM para notas!
      - "marginparsep=5mm"   # Espaço entre o texto e a nota
      - "outer=6cm"        
      - "twoside=true"
    include-in-header: preamble.tex
    
  
  epub: 
    toc: true 
    cover-image: capa.jpg  
    highlight-style: github
    
bibliography: references.bib
csl: abnt.csl          # ABNT para todos os formatos   

execute:
  warning: false
  message: false